name: lfm
channels:
  - pytorch
  - numba/label/dev
  - conda-forge
  - conda-forge/label/gcc7
  - conda-forge/label/broken
  - soumith
  - defaults
dependencies:
  - pip
  - pip:
    - pydicom
    - pyyaml
    - tensorboardX
    - tensorboard
    - Pillow==6.2.2
    - tensorflow==2.4.1
    - higher
    - graphviz
  - numpy==1.19.2
  - torchvision
  - tensorboard==1.13.0
  - tensorboardX==1.6
  - cudatoolkit
  - pytorch==1.7.0
  - torchvision==0.8.0
  - python==3.7.4
  - pydicom
  - tqdm
  - pandas
  - opencv
  - matplotlib

